appType: HTTP #"HTTP", "gRPC", "Task", "Kafka"
logLevel: 6
logFile: "mylogfile.log"
servies_name: test


redis:
  - name: test22
    host : 127.0.0.1
    port : 6379
    password:
    db : 0
    poolSize: 10

httpginServer:
  port: 9999  #服务端口
  appendPprof : true #是否在路由中添加 pprof 路由



